return {
  -- Add the community repository of plugin specifications
  "AstroNvim/astrocommunity",
  -- example of imporing a plugin, comment out to use it or add your own
  -- available plugins can be found at https://github.com/AstroNvim/astrocommunity

  -- { import = "astrocommunity.colorscheme.catppuccin" },
  -- { import = "astrocommunity.completion.copilot-lua-cmp" },
  -- { import = "astrocommunity.pack.tailwindcss" },
  -- { import = "astrocommunity.editing-support.nvim-regexplainer" },
  -- { import = "astrocommunity.editing-support.treesj" },
  -- { import = "astrocommunity.editing-support.ultimate-autopair-nvim" },
  -- { import = "astrocommunity.git.octo-nvim" },
  -- { import = "astrocommunity.motion.marks-nvim" },
  
--  { import = "astrocommunity.git.neogit" },
  -- { import = "astrocommunity.motion.mini-ai" },
  -- { import = "astrocommunity.motion.mini-move" },
  -- { import = "astrocommunity.motion.flash-nvim" },
  -- { import = "astrocommunity.register.nvim-neoclip-lua" },
  -- { import = "astrocommunity.syntax.vim-easy-align" },
  -- { import = "astrocommunity.fuzzy-finder.telescope-zoxide" },
  -- { import = "astrocommunity.editing-support.neogen" },
  { import = "astrocommunity.editing-support.refactoring-nvim" },
  -- { import = "astrocommunity.editing-support.telescore-undo-nvim" },
  { import = "astrocommunity.editing-support.text-case-nvim" },
  { import = "astrocommunity.search.nvim-hlslens" },
  { import = "astrocommunity.editing-support.comment-box-nvim" },
  { import = "astrocommunity.utility.telescope-live-grep-args-nvim" },
  { import = "astrocommunity.utility.nvim-toggler" },
 -- { import = "astrocommunity.lsp.garbage-day-nvim" },


  -- { import = "astrocommunity.programming-language-support.rest-nvim" },
  -- { import = "astrocommunity.editing-support.yanky-nvim" },
  -- { import = "astrocommunity.file-explorer.oil-nvim" },
  -- { import = "astrocommunity.editing-support.nvim-regexplainer" },
  -- { import = "astrocommunity.editing-support.wildfire-nvim" },
  -- { import = "astrocommunity.indent.mini-indentscope" },
  -- { import = "astrocommunity.diagnostics.lsp_lines-nvim" },
  -- { import = "astrocommunity.note-taking.obsidian-nvim" },
  -- { import = "astrocommunity.bars-and-lines.lualine-nvim" },
  -- { import = "astrocommunity.git.gist-nvim" },
  -- { import = "astrocommunity.editing-support.rainbow-delimiters-nvim" },
  -- { import = "astrocommunity." },
  -- { import = "astrocommunity." },
  -- { import = "astrocommunity." },
  -- { import = "astrocommunity." },
  -- { import = "astrocommunity.editing-support.nvim-devdocs" },
  -- { import = "astrocommunity.bars-and-lines.dropbar-nvim" },
  -- { import = "astrocommunity.project.nvim-spectre" },
  -- { import = "astrocommunity.utility.noice-nvim" },
  -- { import = "astrocommunity.scrolling.vim-smoothie" },
  -- { import = "astrocommunity.syntax.vim-sandwich" },
  -- { import = "astrocommunity.color.vim-highlighter" },
  -- { import = "astrocommunity.bars-and-lines.smartcolumn-nvim" },
}
