return {

  "lukas-reineke/indent-blankline.nvim",
  enabled = false,
}

-- return {
--   "lukas-reineke/indent-blankline.nvim",
--   event = "VeryLazy",
--   main = "ibl",
--   enabled = false,
--   config = function()
--     -- vim.opt.list = true
--     -- vim.opt.listchars:append "space:⋅"
--     -- vim.opt.listchars:append "eol:↴"
--     -- vim.opt.termguicolors = true
--     -- vim.cmd [[highlight IndentBlanklineIndent1 guifg=#E06C75 gui=nocombine]]
--     -- vim.cmd [[highlight IndentBlanklineIndent2 guifg=#E5C07B gui=nocombine]]
--     -- vim.cmd [[highlight IndentBlanklineIndent3 guifg=#98C379 gui=nocombine]]
--     -- vim.cmd [[highlight IndentBlanklineIndent4 guifg=#56B6C2 gui=nocombine]]
--     -- vim.cmd [[highlight IndentBlanklineIndent5 guifg=#61AFEF gui=nocombine]]
--     -- vim.cmd [[highlight IndentBlanklineIndent6 guifg=#C678DD gui=nocombine]]
--
--     local highlight = {
--       "RainbowRed",
--       "RainbowYellow",
--       "RainbowBlue",
--       "RainbowOrange",
--       "RainbowGreen",
--       "RainbowViolet",
--       "RainbowCyan",
--     }
--     local hooks = require "ibl.hooks"
--     -- create the highlight groups in the highlight setup hook, so they are reset
--     -- every time the colorscheme changes
--     hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
--       vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
--       vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#E5C07B" })
--       vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
--       vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#D19A66" })
--       vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#98C379" })
--       vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#C678DD" })
--       vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#56B6C2" })
--     end)
--
--     vim.g.rainbow_delimiters = { highlight = highlight }
--     require("ibl").setup {
--       enabled = false,
--       indent = { char = "▏" },
--       exclude = {
--         buftypes = {
--           "nofile",
--           "terminal",
--         },
--         filetypes = {
--           "help",
--           "startify",
--           "aerial",
--           "alpha",
--           "dashboard",
--           "lazy",
--           "neogitstatus",
--           "NvimTree",
--           "neo-tree",
--           "Trouble",
--         },
--       },
--       whitespace = { highlight = { "Whitespace", "NonText" } },
--       scope = {
--         show_start = true,
--         show_end = false,
--         highlight = highlight,
--       },
--     }
--     hooks.register(
--       hooks.type.ACTIVE,
--       function(bufnr)
--         return vim.api.nvim_buf_line_count(bufnr) < 2000
--       end
--     )
--
--
--     hooks.register(hooks.type.SCOPE_HIGHLIGHT, hooks.builtin.scope_highlight_from_extmark)
--   end,
--   keys = {
--     { "<leader>u;", "<cmd>IBLToggle<cr>", desc = "Toggle Indent Blankline" },
--   }
-- }
-- -- vim.g.indent_blankline_use_treesitter = true
